#!/usr/bin/env bash

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

if [[ "$(cat hugo-version.txt)" != "$(hugo version)" ]]; then
    >&2 echo "hugo version mismatch"
    exit 1
fi

open http://localhost:1313 &

hugo server -D
